
name: Building a mOnKeyX Project

on:
  push: 
    branches: [ feat/godot-uk ]
    tags:
      - "v*-test"
  pull_request: 
    branches: [ feat/godot-uk ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.3.0
      - name : exportGame
        uses: firebelley/godot-export@v5.2.1
        with: 
          godot_executable_download_url: https://download.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://download.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./tools/rd-config-test
          relative_export_path: ./
          archive_output: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Test Zips
          path: /home/runner/work/RetroDECK_UK/RetroDECK_UK/*.zip